### ISSUE TITLE
Unit Test Procedure compile error

### ISSUE THREAD

**Issue by skial** [fponticelli/thx.react#13]
Compiling `thx.react.js.hxml` unit tests returns compiler error - 

```
src/thx/react/Binder.hx:57: characters 7-22 : thx.core.Procedure<unbind.T> shoul
d be { fun : thx.core.Procedure.T, arity : Int }
src/thx/react/Binder.hx:57: characters 7-22 : thx.core.Procedure<unbind.T> shoul
d be { fun : thx.core.Procedure.T, arity : Int }
```

Adding `cast` before `handler` in `if (null == handler)` allows it to compile, but as far as I understand abstracts, it should be working as is.

Compiled with Haxe r6619.

**Comment by fponticelli** [comment]
I suppose this happens with RC2? I will update tomorrow and see what happens. I hoped for a painless transition.

**Comment by skial** [comment]
I haven't tried rc2 as I'm normally on the latest nightly anyway. I just
compiled with r6632 and get the same error.

I'm just currently learning promises and its extras and toying with an idea
that works in its most _basic_ form -
https://gist.github.com/skial/5563966#file-main-hx

On Sun, May 12, 2013 at 6:23 PM, Franco Ponticelli <notifications@github.com

**Comment by fponticelli** [comment]
On Sun, May 12, 2013 at 11:51 AM, Skial Bainn notifications@github.comwrote:

> its ex

It should be fixed now ... interesting approach yours ;)
